[theme]
base = "dark"
primaryColor = "#a855f7"
backgroundColor = "#0f1122"
secondaryBackgroundColor = "#1b1f36"
textColor = "#e2e8f0"
font = "sans serif"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true
port = 8501
maxUploadSize = 200

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[runner]
magicEnabled = true
fastReruns = true
